apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: rook-ceph-block
  mountOptions:
    - hard
    - nfsvers=4.1
  # nfs:
  #   path: /tmp
  #   server: 172.17.0.2
  hostPath:
    path: "/mnt/pureserver-mysql"
