# pvc => persistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: default
  labels:
    app: mysql-pvc
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce # pods in the same node can read and write
  resources:
    requests:
      storage: 1Gi